name: Build and lint

on:
  - push
  - pull_request

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-format-18 clang-tidy-18 run-clang-tidy-18

      - name: Check format
        run: |
          find . -path ./build -prune -o -type f -name '*.[c|h]' -print | xargs clang-format-18 --style=file --dry-run -Werror

      - name: Configure
        run: |
          # -DCMAKE_EXPORT_COMPILE_COMMANDS=ON is important for clang-tidy
          cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: |
          cmake --build build

      - name: Lint
        run: |
          run-clang-tidy-18 -p=build

      - name: Run tests
        run: |
          if [ -f "build/src/c_impl/tests" ]; then
            ./build/src/c_impl/tests
          fi
          if [ -f "build/src/bench/benchmark_c" ]; then
            ./build/src/bench/benchmark_c 100 0.05 mm
            ./build/src/bench/benchmark_c 100 0.05 mv
          fi